### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by dirk-thomas** [ros/genlisp#13]
Please release this package into Melodic as soon as time permits.

**Comment by airballking** [comment]
I'm on it.

**Comment by airballking** [comment]
Triggered release. See ros/rosdistro#16845

**Comment by gaya-** [comment]
Thanks, Georg!

Did you also do the roslisp and roslisp_common?

**Comment by airballking** [comment]
Nope, not yet. I think we have to have wait until the required dependencies (incl. this repo) have been merged and built.

**Comment by airballking** [comment]
Close issue as solved because ros/rosdistro#16845 has been merged.
